services:
    blog:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: blog-backend
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            # Ako želiš možeš dodati environment varijable za Laravel
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: base64:SomeRandomKeyHere==

    db:
        image: postgres:15
        container_name: blog-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: blog_app
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
